### ISSUE TITLE
Admin credentials

### ISSUE THREAD

**Issue by dipanshu124** [Kshitij1K/ShopInventoryManager#2]
Admin credentials provided in Readme don't work

**Comment by Kshitij1K** [comment]
Can you try now?

**Comment by dipanshu124** [comment]
Still doesn't work.

**Comment by dipanshu124** [comment]
Apparently a Dbmain file gets automatically created in /main/build and replacing that file with Dbmain file in /database/src make things work.

**Comment by Kshitij1K** [comment]
Nope, no database file gets created. You might have the database file from the previous commit. Replacing it with the database file from the current commit makes it work.
