### ISSUE TITLE
Update Stock Information not working

### ISSUE THREAD

**Issue by dipanshu124** [Kshitij1K/ShopInventoryManager#5]
When trying to update stock information, only the item name and current stock fields get updated. Rest are not updated.

**Comment by Kshitij1K** [comment]
That is not an intended feature anyways. We didn't see any use for that, as information such as name, the selling price, buying price, etc seldom change. Only the stock changes usually.

Anyways, if you want to add an item with different details for an item id, you can try deleting the current item and then adding a new one (the delete item feature is now live).
