### ISSUE TITLE
Missing checks while taking user inputs

### ISSUE THREAD

**Issue by dipanshu124** [Kshitij1K/ShopInventoryManager#6]
Currently, it is the responsibility of the user to ensure correct data type (entrying only numeric fields,  ensuring positive values in certain cases, etc). This makes it very user unfriendly.
Having simple checks in frontend and throwing  errors incase of wrong data types or if some entry is missing would be really helpful.

**Comment by Kshitij1K** [comment]
I have added simple validators for each of the text fields, such as 
1) Only positive integers will be allowed for Item IDs
2) Only positive decimal numbers, with a maximum of 2 decimals after the decimal point, are allowed for all fields representing a monetary value (like price, or available capital).
