### ISSUE TITLE
Delete Employee

### ISSUE THREAD

**Issue by dipanshu124** [Kshitij1K/ShopInventoryManager#7]
In case of Delete Employee, only the Name is required, username and password are redundant.
I would be good to first ask the user what kind of changes they want to make in Employee list (Add Employee or Update Employ or Delete Employ) and then based on that ask only the relevant information.

**Comment by Kshitij1K** [comment]
Actually, only username is required (and checked), as only the username is an unique identifier of the each user.

**Comment by Kshitij1K** [comment]
Won't be able to add different UI pages for each of these, as it will require significant rework on the state machine and UI modules.
