### ISSUE TITLE
Restocking Suggestions

### ISSUE THREAD

**Issue by dipanshu124** [Kshitij1K/ShopInventoryManager#8]
This feature could not be tested due to the over demanding system requirements.
It would be great if you could try reducing the space requirements to maybe 10 Gb at max.

**Comment by Kshitij1K** [comment]
Again, as mentioned in my README, I can't do anything about this (short of reworking the entire CMakeLists of the Google OR-tools library, which is a ton of work). They don't export individual targets for their respective modules, hence, there is no way to instruct CMake to only build those files.
